kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vote
spec:
  host: vote-summit2020.apps-crc.testing
  to:
    kind: Service
    name: vote
    weight: 100
  port:
    targetPort: 8081
  wildcardPolicy: None