kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: vote-service
  #namespace: summit2020
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 0
      maxSurge: 1
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - vote-service-image-stream-s2i
        from:
          kind: ImageStreamTag
          #namespace: summit2020
          name: 'vote-service-image-stream-s2i:latest'
  replicas: 1
  test: false
  selector:
    name: vote-service
  template:
    metadata:
      labels:
        name: vote-service
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          name: vote-service-image-stream-s2i
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler