kind: Service
apiVersion: v1
metadata:
  name: vote
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    deploymentconfig: vote-service
  type: ClusterIP
  sessionAffinity: None